# Generated by Django 4.2.9 on 2025-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='حداکثر 50 کاراکتر', max_length=50, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است'}, max_length=254, unique=True, verbose_name='آدرس ایمیل')),
                ('password_hash', models.CharField(max_length=128, verbose_name='رمز عبور هش شده')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کاربر مدیریت')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش ناموفق')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام نقش قبلا ثبت شده است'}, help_text='نام یکتا برای نقش (حداکثر 50 کاراکتر)', max_length=50, unique=True, verbose_name='نام نقش')),
                ('permissions', models.JSONField(default=list, help_text='لیست دسترسی\u200cهای این نقش به صورت JSON', verbose_name='دسترسی\u200cها')),
                ('permission_group', models.CharField(choices=[('user', 'مدیریت کاربران'), ('content', 'مدیریت محتوا'), ('system', 'تنظیمات سیستم'), ('report', 'گزارشات'), ('finance', 'مالی')], default='user', max_length=20, verbose_name='گروه دسترسی')),
                ('is_default', models.BooleanField(default=False, help_text='آیا این نقش به صورت پیش\u200cفرض به کاربران جدید اختصاص داده شود؟', verbose_name='نقش پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_role'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.role', verbose_name='نقش\u200cهای کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='username_index'),
        ),
    ]
